name: Prepare preview

on:
  pull_request:
    branches:
      - production
      - main
    types: [labeled, opened, synchronize]

jobs:
  preview:
    name: Check preview label
    outputs:
      result: ${{ steps.step1.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Set env variable to true when label is present
        id: step1
        if: ${{ contains( github.event.pull_request.labels.*.name, 'preview' ) }}
        run: echo "::set-output name=result::true"

  changes:
    name: Check changes
    needs: preview
    if: ${{ needs.preview.outputs.result == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      rules: ${{ steps.filter.outputs.rules }}
      firewall: ${{ steps.filter.outputs.firewall }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.4.2
        id: filter
        with:
          filters: |
            rules:
              - 'products/rules/**'
            firewall:
              - 'products/firewall/**'

  create-pr-artifact:
    name: Create PR artifact
    runs-on: ubuntu-latest
    needs: [preview, changes]
    defaults:
      run:
        shell: bash
    steps:
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${PRNUMBER} > ./pr/NUMBER
          touch ./pr/CHANGES
        env:
          # PRNUMBER == '0' => don't deploy preview
          PRNUMBER: ${{ needs.preview.outputs.result == 'true' && format(github.event.number) || '0' }}

      - name: Rules changed
        if: ${{ needs.preview.outputs.result == 'true' && needs.changes.outputs.rules == 'true' }}
        run: echo 'rules' >> ./pr/CHANGES

      - name: Firewall changed
        if: ${{ needs.preview.outputs.result == 'true' && needs.changes.outputs.firewall == 'true' }}
        run: echo 'firewall' >> ./pr/CHANGES

# repeat for other products...

      - name: Create artifact with PR data
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/
          retention-days: 1
